### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Zaydiscool777** [Anon23261/Fun#4]
Couldn't find a way to get to you elsewhere, so I chose this.
I'm currently working on 2 things, so you can decide to take:
- The red pill: Extremely small Unix-like
- The blue pill: Create templates in Python, C, and Snap!
- The purple pill: both at the same time!?!?!?
- The pill: none

**Comment by Anon23261** [comment]
The Purple Pill: Both at the same time

**Comment by Zaydiscool777** [comment]
0k, giving access to both

**Comment by Zaydiscool777** [comment]
Did it! Make sure to create your own branch for both named "anon", please.

**Comment by Anon23261** [comment]
Will do
